name: settings
description: "QuadOS Settings"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  adwaita:
    git: https://github.com/gtk-flutter/adwaita
  flutter:
    sdk: flutter
  libadwaita: ^2.0.2
  libadwaita_bitsdojo: ^0.5.5
  window_manager: ^0.4.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
