name: settings
description: "QuadOS Settings"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  adwaita: ^1.1.0
  adwaita_icons: ^0.2.1
  collection: ^1.18.0
  fast_immutable_collections: ^10.2.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.4.4
  gsettings: ^0.2.8
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  yaru: ^4.1.0

dependency_overrides:
  meta: ^1.15.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true
